version: "3.8"

networks:
  database_net:
    name: database_net
    driver: bridge
  basic_net:
    name: basic_net
    driver: bridge

volumes:
  local-data:
    driver: local

services:
  db:
    image: postgres
    container_name: ${DB_NAME}
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 2345:5432
    networks:
      - database_net