spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: null
    hibernate:
      ddl-auto: create