spring:
  datasource:
    url: "jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASS}"
    tomcat:
      max-active: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
    show-sql: false