openapi: 3.0.3
info:
  title: onboarding-exercise
  description: onboarding-exercise to integrate new comers into tvg team
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names and ids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDetailsDto'
    post:
      summary: Saves user to database and returns their information
      requestBody:
        description: User must provide his/her name
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '200':
          description: A JSON object with user name and id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsDto'

components:
  schemas:
    CreateUserDto:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    UserDetailsDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
